name: Build and Push Docker Image to Docker Hub

on: push
jobs:
  push_to_registry:
    name: push docker image to hub
    runs-on: ubuntu-latest
    steps:
      - name: check repository
        uses: actions/checkout@v4          

      - name: build and push docker image to registry
        uses: docker/build-push-action@v6.4
        with:
          registry: docker.io
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
          image: vouzamo/score-stream
          tags: latest
          dockerfile: ./src/Vouzamo.Web.WebApp/Dockerfile
          push: true
          
